'use client';
import {useEffect,useState} from 'react';
import {ShieldCheck,CalendarDays,Clock3,ArrowRight} from 'lucide-react';
import {useLanguage,LanguagePicker} from '@/components/language';
import {dateLabel,timeLabel} from '@/lib/schedule';
import {money} from '@/lib/prices';
import styles from './confirmation.module.css';
type Receipt={name:string;date:string;start:number;duration:number;inside:number;outside:number;fluid:number;price:number|null};
export default function Confirmation(){const {t,language}=useLanguage();const [receipt,setReceipt]=useState<Receipt|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/confirmation',{signal:controller.signal}).then(async r=>{const data=await r.json() as Receipt&{error?:string};if(!r.ok)throw new Error(data.error);setReceipt(data)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[retry]);
 return <><header><div className="header-identity"><a href="/"><img className="yn-logo" src="/yn-vekst-logo.svg" width="174" height="55" alt="Ytre Namdal Vekst"/></a><a className="brand" href="/">Steam</a></div><LanguagePicker/></header><main className={styles.page}>{loading?<p role="status">{t('Henter bekreftelsen…')}</p>:receipt?<section className={styles.card}><div className={styles.icon}><ShieldCheck size={46}/></div><div className="eyebrow">{t('BESTILLING BEKREFTET')}</div><h1>{t('Timen din er bestilt!')}</h1><p className={styles.greeting}>{t('Vi gleder oss til å se deg,')} {receipt.name}.</p><div className={styles.when}><div><CalendarDays/><span>{dateLabel(receipt.date,language)}</span></div><div><Clock3/><strong>{timeLabel(receipt.start)}–{timeLabel(receipt.start+receipt.duration)}</strong></div></div><dl className={styles.details}><div><dt>{t('Valgt vask')}</dt><dd>{t(receipt.inside&&receipt.outside?'Innvendig og utvendig vask':receipt.inside?'Innvendig vask':'Utvendig vask')}</dd></div><div><dt>{t('Samlet tid')}</dt><dd>{receipt.duration} {t('minutter')}</dd></div>{receipt.fluid===1&&<div><dt>{t('Tillegg')}</dt><dd>{t('Påfyll av spylervæske')}</dd></div>}<div><dt>{t('Pris for bilvask')}</dt><dd>{receipt.price===null?t('Pris avtales'):money(receipt.price,language)}</dd></div></dl><p className="muted">{t('Alle klokkeslett er i norsk tid. Ta vare på bestillingsdetaljene.')}</p><a className={styles.newBooking} href="/">{t('Bestill ny bilvask')}<ArrowRight size={20}/></a></section>:<section className="panel"><h1>{t('Bestillingsbekreftelse')}</h1><p className="error" role="alert">{t(error)}</p><div className="admin-actions"><button className="secondary" onClick={()=>setRetry(v=>v+1)}>{t('Prøv igjen.')}</button><a href="/" className="primary">{t('Tilbake til bestilling')}</a></div></section>}</main></>;
}

