import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {washDuration,available} from '../lib/schedule.ts';
import {INSERT_BOOKING} from '../lib/booking-sql.ts';
const settings={insideMinutes:45,outsideMinutes:30};
assert.equal(washDuration(settings,false,true,true),45);
assert.equal(washDuration(settings,true,false,true),60);
assert.equal(washDuration(settings,true,true,true),105);
assert.equal(washDuration(settings,true,true,false),75);
assert.equal(washDuration(settings,false,false,true),0);
assert.ok(!available('2030-01-08',105,[]).includes(600));
assert.ok(available('2030-01-08',75,[]).includes(600));
const db=new DatabaseSync(':memory:');
for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())db.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const date='2030-01-08';
const insert=(id,start,duration)=>db.prepare(INSERT_BOOKING).run(id,'Test','12345678',date,start,duration,0,1,Date.now(),0,19900,1,0,date,start+duration,start,date,date,0,720,date);
assert.equal(insert('large',480,45).changes,1);
assert.equal(insert('overlap',510,30).changes,0);
assert.equal(insert('next',525,30).changes,1);
const row=db.prepare('SELECT large_car,duration,price FROM bookings WHERE id=?').get('large');assert.equal(row.large_car,1);assert.equal(row.duration,45);assert.equal(row.price,19900);
db.close();console.log('PASS: large-car extra time per wash, combined duration, lunch boundary, stored car size and overlap prevention.');
