import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
import {createRequire} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const require=createRequire(import.meta.url);
// Verify additive migration preserves a pre-existing restricted account.
const legacy=new DatabaseSync(':memory:');
const migrations=fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort();
for(const file of migrations.slice(0,-1))legacy.exec(fs.readFileSync('drizzle/'+file,'utf8'));
legacy.prepare('INSERT INTO viewers (id,username,hash,salt,version,active) VALUES (?,?,?,?,?,?)').run('legacy','legacy-reader','fixture-hash','fixture-salt',7,1);
legacy.exec(fs.readFileSync('drizzle/'+migrations.at(-1),'utf8'));
assert.equal(legacy.prepare('SELECT role FROM viewers WHERE id=?').get('legacy').role,'viewer');
assert.equal(legacy.prepare('SELECT version FROM viewers WHERE id=?').get('legacy').version,7);legacy.close();
const sqlite=new DatabaseSync(':memory:');
for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort()) sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));
const DB={prepare(sql){let params=[];const execute=method=>{const statement=sqlite.prepare(sql);return /\?\d/.test(sql)?statement[method](Object.fromEntries(params.map((p,i)=>[String(i+1),p]))):statement[method](...params);};return {bind(...values){params=values;return this},async first(){return execute('get')??null},async all(){return {results:execute('all')}},async run(){return {meta:execute('run')}}};},async batch(statements){const result=[];for(const stmt of statements)result.push(await stmt.run());return result}};
const cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const exports={};cache.set(file,exports);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports,require:name=>name==='cloudflare:workers'?{env:{DB}}:name.startsWith('node:')?require(name):load(name.startsWith('@/')?name.slice(2)+'.ts':path.resolve(path.dirname(file),name)+'.ts'),crypto,Request,Response,URL,TextEncoder,TextDecoder,SyntaxError,AbortSignal,Date,Intl},{filename:file});return exports;}
const server=load('lib/server.ts'),admin=load('app/api/admin/route.ts'),users=load('app/api/users/route.ts');
const adminPassword='Admin-test-9274';const salt=crypto.randomUUID();sqlite.prepare('INSERT INTO admins(id,username,hash,salt,version) VALUES(1,?,?,?,2)').run('admin',await server.passwordHash(adminPassword,salt),salt);
let requestNumber=0;
function req(body,cookie='',route='admin'){return new Request('http://localhost/api/'+route,{method:body?'POST':'GET',headers:{origin:'http://localhost','content-type':'application/json','cf-connecting-ip':String(++requestNumber),cookie},...(body?{body:JSON.stringify(body)}:{})});}
async function login(username,password){const response=await admin.POST(req({action:'login',username,password}));assert.equal(response.status,200);return response.headers.get('set-cookie').split(';')[0];}
const adminCookie=await login('admin',adminPassword);
assert.equal(await server.authorized(req(null,adminCookie)),true);
assert.equal((await users.POST(req({action:'create',username:'worker',password:'Work-test-9381'},adminCookie))).status,201);
const stored=sqlite.prepare('SELECT * FROM viewers').get();assert.notEqual(stored.hash,'Work-test-9381');assert.equal(stored.active,1);assert.equal(stored.role,'viewer');
assert.equal((await users.POST(req({action:'create',username:'WORKER',password:'Work-test-9381'},adminCookie))).status,409);
assert.equal((await users.POST(req({action:'create',username:'ADMIN',password:'Work-test-9381'},adminCookie))).status,409);
assert.equal((await users.POST(req({action:'create',username:'short',password:'123'},adminCookie))).status,400);
const viewerCookie=await login('WORKER','Work-test-9381');
assert.equal(await server.authorized(req(null,viewerCookie)),false);
const bookingId=crypto.randomUUID();sqlite.prepare('INSERT INTO bookings(id,name,phone,date,start,duration,inside,outside,created) VALUES(?,?,?,?,480,30,0,1,?)').run(bookingId,'Test','12345678','2026-09-11',Date.now());
const schedule=await admin.GET(new Request('http://localhost/api/admin?date=2026-09-11',{headers:{cookie:viewerCookie}}));assert.equal(schedule.status,200);const body=await schedule.json();assert.equal(body.role,'viewer');assert.equal(body.username,'worker');assert.equal(body.bookings.length,1);
assert.equal((await admin.POST(req({action:'cancel-booking',id:bookingId},viewerCookie))).status,403);
assert.equal((await admin.POST(req({action:'credentials',username:'worker',currentPassword:adminPassword,password:'Replacement-9381'},viewerCookie))).status,403);
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM bookings').get().n,1);
for(const name of ['prices','contact','booking-settings','closed-dates','recovery-email','users']){
 const route=load('app/api/'+name+'/route.ts');const response=await route.POST(req({action:'create',username:'intruder',password:'Secret-8931'},viewerCookie,name));assert.ok([401,403].includes(response.status),name+' must reject viewer writes');
 if(['users','recovery-email','closed-dates'].includes(name))assert.ok([401,403].includes((await route.GET(req(null,viewerCookie,name))).status));
}
assert.equal((await users.POST(req({action:'access',id:stored.id,active:false},adminCookie))).status,200);
assert.equal((await admin.GET(req(null,viewerCookie))).status,401);
assert.equal((await admin.POST(req({action:'login',username:'worker',password:'Work-test-9381'}))).status,401);
assert.equal((await users.POST(req({action:'access',id:stored.id,active:true},adminCookie))).status,200);
assert.equal((await admin.GET(req(null,viewerCookie))).status,401);
const renewed=await login('worker','Work-test-9381');assert.equal((await admin.GET(req(null,renewed))).status,200);
assert.equal((await admin.POST(req({action:'logout'},renewed))).status,200);assert.equal((await admin.GET(req(null,renewed))).status,401);
assert.equal((await admin.POST(req({action:'duration',id:bookingId,duration:60,expectedDuration:30},viewerCookie))).status,401);
assert.equal((await admin.POST(req({action:'duration',id:bookingId,duration:60,expectedDuration:30},adminCookie))).status,200);
assert.equal(sqlite.prepare('SELECT duration FROM bookings WHERE id=?').get(bookingId).duration,60);
assert.equal((await admin.POST(req({action:'duration',id:bookingId,duration:45,expectedDuration:30},adminCookie))).status,409);
const conflictId=crypto.randomUUID();sqlite.prepare('INSERT INTO bookings(id,name,phone,date,start,duration,inside,outside,created) VALUES(?,?,?,?,540,30,0,1,?)').run(conflictId,'Conflict','12345678','2026-09-11',Date.now());
assert.equal((await admin.POST(req({action:'duration',id:bookingId,duration:90,expectedDuration:60},adminCookie))).status,409);
assert.equal((await admin.POST(req({action:'duration',id:bookingId,duration:0,expectedDuration:60},adminCookie))).status,400);
assert.equal((await admin.POST(req({action:'duration',id:bookingId,duration:45,expectedDuration:60},adminCookie))).status,200);
assert.equal((await admin.POST(req({action:'cancel-booking',id:bookingId},adminCookie))).status,200);
assert.equal((await admin.POST(req({action:'credentials',username:'worker',currentPassword:adminPassword,password:'Replacement-9381'},adminCookie))).status,409);
assert.equal((await users.POST(new Request('http://localhost/api/users',{method:'POST',headers:{origin:'https://example.org'}}))).status,403);
assert.equal((await admin.GET(req(null))).status,401);
const settingsRoute=load('app/api/booking-settings/route.ts');
assert.equal((await (await settingsRoute.GET()).json()).largeCarPercent,0);
assert.equal((await (await settingsRoute.GET()).json()).mapsUrl,'https://maps.app.goo.gl/eLbrjaFsUCS2t9VNA');
const mapSettings={weeksAhead:8,insideMinutes:30,outsideMinutes:30,weekdays:44,mapsUrl:'https://www.google.com/maps/place/Steam'};
assert.equal((await settingsRoute.POST(req(mapSettings,adminCookie))).status,200);
assert.equal((await (await settingsRoute.GET()).json()).mapsUrl,mapSettings.mapsUrl);
for(const mapsUrl of ['javascript:alert(1)','https://google.com.evil.test/maps','https://example.com','https://user@maps.app.goo.gl/test','http://maps.app.goo.gl/test'])assert.equal((await settingsRoute.POST(req({...mapSettings,mapsUrl},adminCookie))).status,400);
assert.equal((await settingsRoute.POST(req(mapSettings,viewerCookie))).status,401);
assert.equal((await settingsRoute.POST(req({weeksAhead:8,insideMinutes:45,outsideMinutes:60,weekdays:62},adminCookie))).status,200);
const savedSettings=await (await settingsRoute.GET()).json();assert.equal(savedSettings.insideMinutes,45);assert.equal(savedSettings.outsideMinutes,60);assert.equal(savedSettings.weekdays,62);
assert.equal(savedSettings.mapsUrl,mapSettings.mapsUrl);
sqlite.prepare('UPDATE booking_settings SET large_car_percent=25').run();
assert.equal((await settingsRoute.POST(req({weeksAhead:8,insideMinutes:30,outsideMinutes:30,weekdays:62},adminCookie))).status,200);
const preservedSettings=await (await settingsRoute.GET()).json();assert.equal(preservedSettings.largeCarPercent,25);assert.equal(preservedSettings.mapsUrl,mapSettings.mapsUrl);
sqlite.prepare('UPDATE booking_settings SET large_car_percent=0').run();
const availabilityRoute=load('app/api/availability/route.ts');
for(const [start,duration] of [[480,195],[720,180]])sqlite.prepare('INSERT INTO bookings(id,name,phone,date,start,duration,inside,outside,created) VALUES(?,?,?, ?,?,?,0,1,?)').run(crypto.randomUUID(),'Calendar test','12345678','2030-01-08',start,duration,Date.now());
const fullMonth=await (await availabilityRoute.GET(new Request('http://localhost/api/availability?month=2030-01&duration=195'))).json();assert.ok(fullMonth.fullDates.includes('2030-01-08'));
const shortMonth=await (await availabilityRoute.GET(new Request('http://localhost/api/availability?month=2030-01&duration=15'))).json();assert.ok(!shortMonth.fullDates.includes('2030-01-08'));
assert.ok(!fullMonth.fullDates.includes('2030-01-06'), 'Closed Sundays must not be marked fully booked');
const pastMonth=await (await availabilityRoute.GET(new Request('http://localhost/api/availability?month=2020-01&duration=195'))).json();assert.equal(pastMonth.fullDates.length,0,'Past dates must not be marked fully booked');
sqlite.prepare('INSERT INTO closed_dates(date) VALUES(?)').run('2030-01-08');
const closedMonth=await (await availabilityRoute.GET(new Request('http://localhost/api/availability?month=2030-01&duration=195'))).json();
assert.ok(closedMonth.closedDates.includes('2030-01-08'));assert.ok(!closedMonth.fullDates.includes('2030-01-08'),'Explicit closures take precedence over full bookings');
sqlite.prepare('DELETE FROM closed_dates WHERE date=?').run('2030-01-08');
assert.equal((await availabilityRoute.GET(new Request('http://localhost/api/availability?month=2030-01&duration=17'))).status,400);
assert.equal((await availabilityRoute.GET(new Request('http://localhost/api/availability?month=2030-01'))).status,200);
sqlite.prepare("DELETE FROM bookings WHERE name='Calendar test'").run();
for(const minutes of [0,16,121,150])assert.equal((await settingsRoute.POST(req({weeksAhead:8,insideMinutes:minutes,outsideMinutes:30,weekdays:44},adminCookie))).status,400);
for(const weekdays of [-1,128,1.5,1,64,65,127])assert.equal((await settingsRoute.POST(req({weeksAhead:8,insideMinutes:30,outsideMinutes:30,weekdays},adminCookie))).status,400);
assert.equal((await settingsRoute.POST(req({weeksAhead:8,insideMinutes:30,outsideMinutes:30,weekdays:0},adminCookie))).status,200);
const scheduleRules=load('lib/schedule.ts');
assert.equal(scheduleRules.blocked('2030-01-06',65),false);
assert.equal(scheduleRules.blocked('2030-01-07',65),true);
assert.deepEqual(Array.from(scheduleRules.available('2030-01-06',45,[],0)),[]);
const slots=Array.from(scheduleRules.available('2030-01-06',45,[{start:480,duration:60}],65));
assert.ok(slots.includes(540));assert.ok(!slots.includes(525));assert.ok(!slots.includes(675));assert.ok(slots.includes(840));
assert.ok(!scheduleRules.available('2030-01-06',120,[],65).includes(795));
const polishRoute=load('app/api/polish-settings/route.ts');
assert.equal((await (await polishRoute.GET(req(null,adminCookie))).json()).enabled,0);
assert.equal((await polishRoute.POST(req({enabled:true,minutes:60,price:50000},viewerCookie))).status,403);
const bookingRoute=load('app/api/bookings/route.ts');const tomorrow=new Date(scheduleRules.today()+'T12:00:00Z');tomorrow.setUTCDate(tomorrow.getUTCDate()+1);while([0,6].includes(tomorrow.getUTCDay()))tomorrow.setUTCDate(tomorrow.getUTCDate()+1);const polishDate=tomorrow.toISOString().slice(0,10);
const polishBody={name:'Polish test',phone:'12345678',date:polishDate,start:480,inside:false,outside:false,polish:true,expectedDuration:60,expectedPrice:50000};
assert.equal((await bookingRoute.POST(req(polishBody))).status,409);
assert.equal((await polishRoute.POST(req({enabled:true,minutes:60,price:50000},adminCookie))).status,200);
assert.equal((await polishRoute.POST(req({enabled:true,minutes:17,price:50000},adminCookie))).status,400);
sqlite.prepare('UPDATE booking_settings SET weekdays=127').run();
assert.equal((await bookingRoute.POST(req(polishBody))).status,400);
assert.equal((await bookingRoute.POST(req({...polishBody,inside:true}))).status,400);
sqlite.prepare('INSERT INTO prices(id,outside) VALUES(1,19900) ON CONFLICT(id) DO UPDATE SET outside=19900').run();
for(const largeCarPercent of [-1,1.5,1001,'20',null])assert.equal((await settingsRoute.POST(req({...mapSettings,largeCarPercent},adminCookie))).status,400);
assert.equal((await settingsRoute.POST(req({...mapSettings,weekdays:62,largeCarPercent:20},adminCookie))).status,200);
assert.equal((await (await settingsRoute.GET()).json()).largeCarPercent,20);
assert.equal((await bookingRoute.POST(req({...polishBody,outside:true,largeCar:true,expectedDuration:105,expectedPrice:69900}))).status,409);
const polishBooking=await bookingRoute.POST(req({...polishBody,outside:true,largeCar:true,expectedDuration:105,expectedPrice:83880}));assert.equal(polishBooking.status,201);const polishReceipt=await polishBooking.json();assert.equal(polishReceipt.duration,105);assert.equal(polishReceipt.price,83880);
assert.equal((await settingsRoute.POST(req({...mapSettings,largeCarPercent:0},adminCookie))).status,200);
assert.equal(sqlite.prepare('SELECT price FROM bookings WHERE id=?').get(polishReceipt.id).price,83880);
assert.equal(sqlite.prepare('SELECT polish FROM bookings WHERE id=?').get(polishReceipt.id).polish,1);
assert.equal((await polishRoute.POST(req({enabled:false,minutes:90,price:60000},adminCookie))).status,200);
assert.equal((await bookingRoute.POST(req({...polishBody,start:600}))).status,409);
assert.equal(sqlite.prepare('SELECT duration FROM bookings WHERE id=?').get(polishReceipt.id).duration,105);
const priceRules=load('lib/prices.ts');assert.equal(priceRules.withPolish(19900,true,50000),69900);assert.equal(priceRules.withPolish(19900,true,null),null);assert.equal(scheduleRules.washDuration({insideMinutes:30,outsideMinutes:45,polishMinutes:60},true,true,true,true),165);
const examplePrices={inside:29900,outside:19900,fluid:3900};
assert.equal(priceRules.bookingTotal(examplePrices,true,true,true,true,69900,true,20),147540);
assert.equal(priceRules.bookingTotal(examplePrices,true,true,true,true,69900,true,0),123600);
assert.equal(priceRules.bookingTotal(examplePrices,true,true,true,true,69900,false,20),123600);
assert.equal(priceRules.bookingTotal(examplePrices,true,false,false,false,null,true,20),35880);
assert.equal(priceRules.bookingTotal({...examplePrices,inside:null},true,false,false,false,null,true,20),null);
assert.equal(priceRules.servicePrice(19999,true,15),22999);
// Role changes invalidate both upgrades and downgrades, and cannot create admins.
assert.equal((await users.POST(req({action:'create',username:'manager',password:'Manager-test-9381',role:'manager'},adminCookie))).status,201);
assert.equal((await users.POST(req({action:'create',username:'escalation',password:'Manager-test-9381',role:'admin'},adminCookie))).status,400);
const manager=sqlite.prepare('SELECT id FROM viewers WHERE username=?').get('manager');
let managerCookie=await login('manager','Manager-test-9381');
assert.equal((await server.currentUser(req(null,managerCookie))).role,'manager');
assert.equal(await server.authorized(req(null,managerCookie)),false);
const managerSchedule=await admin.GET(req(null,managerCookie));assert.equal(managerSchedule.status,200);assert.equal((await managerSchedule.json()).role,'manager');
const userList=await (await users.GET(req(null,adminCookie))).json();assert.ok(userList.users.every(user=>!('hash' in user)&&!('salt' in user)));
assert.equal((await users.GET(req(null,managerCookie))).status,403);
for(const name of ['prices','contact','booking-settings','closed-dates','recovery-email','users','polish-settings']){
 const route=load('app/api/'+name+'/route.ts');assert.ok([401,403].includes((await route.POST(req({action:'create'},managerCookie,name))).status),name+' rejects manager writes');
}
assert.equal((await admin.POST(req({action:'credentials',username:'manager',currentPassword:adminPassword,password:'Replacement-9381'},managerCookie))).status,403);
assert.equal((await users.POST(req({action:'role',id:manager.id,role:'admin'},adminCookie))).status,400);
const readCookie=await login('worker','Work-test-9381');
for(const action of ['progress','duration','reschedule','cancel-booking'])assert.equal((await admin.POST(req({action,id:polishReceipt.id,status:1,expectedStatus:0,duration:120,expectedDuration:105,date:polishDate,start:600,expectedDate:polishDate,expectedStart:480},readCookie))).status,403);
assert.equal(sqlite.prepare('SELECT duration,status,start FROM bookings WHERE id=?').get(polishReceipt.id).duration,105);
assert.equal((await users.POST(req({action:'role',id:stored.id,role:'manager'},adminCookie))).status,200);
assert.equal((await admin.GET(req(null,readCookie))).status,401);
const upgradedCookie=await login('worker','Work-test-9381');assert.equal((await server.currentUser(req(null,upgradedCookie))).role,'manager');
assert.equal((await users.POST(req({action:'role',id:stored.id,role:'viewer'},adminCookie))).status,200);
assert.equal((await admin.GET(req(null,upgradedCookie))).status,401);
assert.equal((await users.POST(req({action:'role',id:manager.id,role:'viewer'},adminCookie))).status,200);
assert.equal((await admin.GET(req(null,managerCookie))).status,401);
assert.equal((await users.POST(req({action:'role',id:manager.id,role:'manager'},adminCookie))).status,200);
managerCookie=await login('manager','Manager-test-9381');
// Stored roles outside the supported set fail closed, even with a valid session.
sqlite.prepare('UPDATE viewers SET role=? WHERE id=?').run('admin',manager.id);
assert.equal(await server.currentUser(req(null,managerCookie)),null);
sqlite.prepare('UPDATE viewers SET role=? WHERE id=?').run('manager',manager.id);
const deleteCookie=await login('worker','Work-test-9381');
const statusRoute=load('app/api/wash-status/route.ts');
const lookup={code:polishReceipt.id,lookup:'12345678'};
assert.equal((await statusRoute.POST(req(lookup))).status,403);
assert.equal((await settingsRoute.POST(req({action:'status-enabled',statusEnabled:true},deleteCookie))).status,401);
assert.equal((await settingsRoute.POST(req({action:'status-enabled',statusEnabled:true},adminCookie))).status,200);
const codeHelper=load('lib/booking-code.ts');
const shortCode=await codeHelper.bookingCode(polishReceipt.id);
assert.match(shortCode,/^[23456789ABCDEFGHJKLMNPQRSTUVWXYZ]{6}$/);
assert.equal(await codeHelper.bookingCode(polishReceipt.id),shortCode);
assert.equal((await statusRoute.POST(req({...lookup,code:shortCode.toLowerCase()}))).status,200);
assert.equal((await statusRoute.POST(req({...lookup,code:shortCode,lookup:'wrong'}))).status,404);
assert.equal((await statusRoute.POST(req({...lookup,lookup:'wrong'}))).status,404);
assert.equal((await statusRoute.POST(req({...lookup,code:'wrong'}))).status,404);
assert.equal((await admin.POST(req({action:'progress',id:polishReceipt.id,status:1,expectedStatus:0}))).status,401);
assert.equal((await admin.POST(req({action:'progress',id:polishReceipt.id,status:1,expectedStatus:0},deleteCookie))).status,403);
assert.equal((await admin.POST(req({action:'progress',id:polishReceipt.id,status:1,expectedStatus:0},managerCookie))).status,200);
assert.equal((await (await statusRoute.POST(req(lookup))).json()).status,1);
assert.equal((await admin.POST(req({action:'progress',id:polishReceipt.id,status:2,expectedStatus:0},adminCookie))).status,409);
assert.equal((await admin.POST(req({action:'progress',id:polishReceipt.id,status:2,expectedStatus:1},adminCookie))).status,200);
assert.equal((await (await statusRoute.POST(req({...lookup,lookup:'Polish test'}))).json()).status,2);
assert.equal((await admin.POST(req({action:'duration',id:polishReceipt.id,duration:120,expectedDuration:105},managerCookie))).status,200);
assert.equal((await admin.POST(req({action:'duration',id:polishReceipt.id,duration:135,expectedDuration:105},managerCookie))).status,409);
assert.equal((await settingsRoute.POST(req({...mapSettings,weekdays:62},adminCookie))).status,200);
const moveResponse=await admin.POST(req({action:'reschedule',id:polishReceipt.id,date:polishDate,start:720,expectedDate:polishDate,expectedStart:480},managerCookie));assert.equal(moveResponse.status,200,JSON.stringify(await moveResponse.json()));
assert.equal(sqlite.prepare('SELECT start FROM bookings WHERE id=?').get(polishReceipt.id).start,720);
const cancelId=crypto.randomUUID();sqlite.prepare('INSERT INTO bookings(id,name,phone,date,start,duration,inside,outside,created) VALUES(?,?,?,?,480,30,0,1,?)').run(cancelId,'Manager cancellation','12345678',polishDate,Date.now());
assert.equal((await admin.POST(req({action:'cancel-booking',id:cancelId},managerCookie))).status,200);
assert.equal(sqlite.prepare('SELECT id FROM bookings WHERE id=?').get(cancelId),undefined);
assert.equal((await settingsRoute.POST(req({action:'status-enabled',statusEnabled:false},adminCookie))).status,200);
assert.equal((await statusRoute.POST(req(lookup))).status,403);
assert.equal((await admin.POST(req({action:'progress',id:polishReceipt.id,status:0,expectedStatus:2},deleteCookie))).status,403);
assert.equal((await users.POST(req({action:'delete',id:stored.id},deleteCookie))).status,403);
assert.equal((await users.POST(req({action:'delete',id:stored.id}))).status,403);
const bookingCount=sqlite.prepare('SELECT COUNT(*) AS n FROM bookings').get().n;
assert.equal((await users.POST(req({action:'delete',id:stored.id},adminCookie))).status,200);
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM viewers WHERE id=?').get(stored.id).n,0);
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM sessions WHERE viewer_id=?').get(stored.id).n,0);
assert.equal((await admin.GET(req(null,deleteCookie))).status,401);
assert.equal((await admin.POST(req({action:'login',username:'worker',password:'Work-test-9381'}))).status,401);
assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM bookings').get().n,bookingCount);
assert.equal(await server.authorized(req(null,adminCookie)),true);
assert.equal((await users.POST(req({action:'delete',id:stored.id},adminCookie))).status,404);
sqlite.prepare('UPDATE sessions SET expires=0').run();assert.equal(await server.authorized(req(null,adminCookie)),false);
sqlite.close();console.log('PASS: migration preserves read-only users, manager order actions, viewer mutation denial, role upgrade/downgrade session invalidation, escalation denial, real password login, role-bound sessions, schedule access, every privileged API blocked for viewers, unchanged booking after rejected cancellation, admin cancellation, username collisions, disable/reactivate, stale sessions, logout, expiry and origin protection.');
