'use client';
import {useEffect,useState} from 'react';
import {Mail,MapPin,Phone,UserRound} from 'lucide-react';
import {useLanguage} from './language';
type Contact={name:string;phone:string;email:string;address:string;vipps:string};
const empty:Contact={name:'',phone:'',email:'',address:'',vipps:''};
export function ContactSection({edit=false}:{edit?:boolean}){
 const {t}=useLanguage();const [contact,setContact]=useState<Contact>(empty),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');fetch('/api/contact',{signal:controller.signal}).then(async r=>{const data=await r.json() as Contact&{error?:string};if(!r.ok)throw new Error(data.error);setContact(data)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[retry]);
 async function save(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setSaved(false);setError('');try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(contact)});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error);setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Kunne ikke lagre kontaktinformasjonen.')}finally{setBusy(false)}}
 return <section className={'contact-section '+(edit?'contact-editor panel':'')} aria-labelledby={edit?'contact-editor-title':'contact-title'}><div><div className="eyebrow">{t('STEAM BILVASK')}</div><h2 id={edit?'contact-editor-title':'contact-title'}>{t(edit?'Rediger kontaktinformasjon':'Kontakt oss')}</h2>{edit&&<p className="muted">{t('Opplysningene vises nederst på bestillingssiden. Tomme felt skjules.')}</p>}</div>{loading?<p role="status">{t('Laster kontaktinformasjon…')}</p>:edit?<form onSubmit={save}><fieldset disabled={busy} className="contact-fields"><label>{t('Kontaktperson / virksomhet')}<input maxLength={120} value={contact.name} onChange={e=>{setSaved(false);setContact({...contact,name:e.target.value})}}/></label><label>{t('Telefonnummer')}<input type="tel" maxLength={30} value={contact.phone} onChange={e=>{setSaved(false);setContact({...contact,phone:e.target.value})}}/></label><label>{t('E-post')}<input type="email" maxLength={254} value={contact.email} onChange={e=>{setSaved(false);setContact({...contact,email:e.target.value})}}/></label><label>{t('Besøksadresse')}<input maxLength={300} value={contact.address} onChange={e=>{setSaved(false);setContact({...contact,address:e.target.value})}}/></label><label>{t('Vipps-nummer')}<input type="tel" maxLength={30} value={contact.vipps} onChange={e=>{setSaved(false);setContact({...contact,vipps:e.target.value})}}/><small>{t('Vises i betalingsfeltet. La stå tomt for å skjule.')}</small></label></fieldset><button className="primary" disabled={busy}>{t(busy?'Lagrer…':'Lagre kontaktinformasjon')}</button>{saved&&<p className="contact-saved" role="status">{t('Kontaktinformasjonen er lagret.')}</p>}</form>:<div className="contact-items">{contact.name&&<p><UserRound size={20}/><span>{contact.name}</span></p>}{contact.phone&&<a href={'tel:'+contact.phone.replace(/[^+\d]/g,'')}><Phone size={20}/><span>{contact.phone}</span></a>}{contact.email&&<a href={'mailto:'+contact.email}><Mail size={20}/><span>{contact.email}</span></a>}{contact.address&&<p><MapPin size={20}/><span>{contact.address}</span></p>}{!error&&![contact.name,contact.phone,contact.email,contact.address].some(Boolean)&&<p>{t('Kontaktinformasjon kommer snart.')}</p>}</div>}{error&&<p className="error" role="alert">{t(error)} <button type="button" className="secondary" onClick={()=>setRetry(v=>v+1)}>{t('Prøv igjen.')}</button></p>}</section>
}
