'use client';
import {useEffect,useState} from 'react';
import {useLanguage} from './language';
export function PolishSettings(){
  const {t}=useLanguage();const [enabled,setEnabled]=useState(false),[minutes,setMinutes]=useState('60'),[price,setPrice]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[retry,setRetry]=useState(0);
  useEffect(()=>{const c=new AbortController();setError('');fetch('/api/polish-settings',{signal:c.signal}).then(async r=>{const b=await r.json() as {enabled:number;minutes:number;price:number|null;error?:string};if(!r.ok)throw new Error(b.error);setEnabled(b.enabled===1);setMinutes(String(b.minutes));setPrice(b.price===null?'':String(b.price/100));setReady(true)}).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[retry]);
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setSaved(false);try{const r=await fetch('/api/polish-settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled,minutes:Number(minutes),price:price.trim()===''?null:Math.round(Number(price)*100)})});const b=await r.json() as {error?:string};if(!r.ok)throw new Error(b.error);setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Prøv igjen.')}finally{setBusy(false)}}
  return <section className="panel polish-settings"><h2>{t('Bilpolering')}</h2><p className="muted">{t('Deaktivert som standard. Aktiver for å vise polering på bestillingssiden. Eksisterende bestillinger beholdes.')}</p>{!ready&&!error&&<p>{t('Laster…')}</p>}{ready&&<form onSubmit={save} onChange={()=>setSaved(false)}><label className="polish-toggle"><input type="checkbox" checked={enabled} disabled={busy} onChange={e=>setEnabled(e.target.checked)}/>{t('Tilby bilpolering')}</label><div className="form-grid"><label>{t('Arbeidstid i minutter')}<input required type="number" min="15" max="180" step="15" value={minutes} disabled={busy} onChange={e=>setMinutes(e.target.value)}/></label><label>{t('Pris')} · NOK<input type="number" min="0" max="100000" step="0.01" value={price} disabled={busy} onChange={e=>setPrice(e.target.value)}/></label></div><p className="muted">{t('Tom pris betyr at pris avtales. Ved flere tjenester legges tid og pris sammen.')}</p><button className="primary" disabled={busy}>{t(busy?'Lagrer…':'Lagre innstillinger')}</button></form>}{error&&<p className="error" role="alert">{t(error)}{!ready&&<button className="secondary" onClick={()=>setRetry(n=>n+1)}>{t('Prøv igjen.')}</button>}</p>}{saved&&<p className="success" role="status">{t('Innstillingene er lagret.')}</p>}</section>;
}
