'use client';
import {useEffect,useState} from 'react';
import {useLanguage} from './language';
import type {Prices} from '@/lib/prices';
export function PriceEditor(){const {t}=useLanguage();const [inside,setInside]=useState(''),[outside,setOutside]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{const controller=new AbortController();setError('');fetch('/api/prices',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Kunne ikke hente prisene.');const p=await r.json() as Prices;setInside(p.inside===null?'':String(p.inside/100));setOutside(p.outside===null?'':String(p.outside/100));setReady(true)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)});return()=>controller.abort()},[retry]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setSaved(false);try{const parse=(s:string)=>s.trim()===''?null:Math.round(Number(s.replace(',','.'))*100);const r=await fetch('/api/prices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({inside:parse(inside),outside:parse(outside)})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error);setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Kunne ikke lagre prisene.')}finally{setBusy(false)}}
 return <section className="panel price-editor"><h2>{t('Priser for bilvask')}</h2><p className="muted">{t('Priser i kroner. Tomt felt betyr at pris avtales. Endringer gjelder nye bestillinger.')}</p>{ready&&<form onSubmit={save}><div className="form-grid"><label>{t('Innvendig vask')} · NOK<input type="number" min="0" max="100000" step="0.01" value={inside} onChange={e=>{setInside(e.target.value);setSaved(false)}}/></label><label>{t('Utvendig vask')} · NOK<input type="number" min="0" max="100000" step="0.01" value={outside} onChange={e=>{setOutside(e.target.value);setSaved(false)}}/></label></div><button className="primary" disabled={busy}>{t(busy?'Lagrer…':'Lagre priser')}</button></form>}{error&&<p className="error" role="alert">{t(error)} {!ready&&<button className="secondary" onClick={()=>setRetry(r=>r+1)}>{t('Prøv igjen.')}</button>}</p>}{saved&&<p role="status">{t('Prisene er lagret.')}</p>}</section>
}
