'use client';
import {useEffect,useState} from 'react';
import {useLanguage} from './language';
export function RecoveryEmail(){
 const {t}=useLanguage();const [email,setEmail]=useState(''),[emailConfigured,setEmailConfigured]=useState<boolean|null>(null),[password,setPassword]=useState(''),[error,setError]=useState(''),[saved,setSaved]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/recovery-email',{signal:controller.signal}).then(async r=>{const data=await r.json() as {email:string;emailConfigured:boolean;error?:string};if(!r.ok)throw new Error(data.error);setEmail(data.email);setEmailConfigured(data.emailConfigured)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[]);
 async function save(e:React.SubmitEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setSaved(false);try{const r=await fetch('/api/recovery-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json() as {error?:string};if(!r.ok)throw new Error(data.error);setPassword('');setSaved(true)}catch(e){setError(e instanceof Error?e.message:'Prøv igjen.')}finally{setBusy(false)}}
 return <section className="panel settings"><h2>{t('Gjenoppretting av passord')}</h2><p className="muted">{t('Hit sendes lenken hvis du glemmer passordet. Adressen vises ikke til kundene.')}</p>{emailConfigured===false&&<p className="notice" role="status">{t('E-postutsending er ikke satt opp. Gjenopprettingsadressen kan lagres, men reset-lenker kan ikke sendes før e-posttjenesten er konfigurert.')}</p>}{loading?<p role="status">{t('Laster…')}</p>:<form onSubmit={save}><label>{t('E-post for gjenoppretting')}<input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>{setEmail(e.target.value);setSaved(false)}}/></label><label>{t('Nåværende passord')}<input type="password" required maxLength={200} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={busy}>{t(busy?'Lagrer…':'Lagre e-postadresse')}</button></form>}{error&&<p className="error" role="alert">{t(error)}</p>}{saved&&<p className="success" role="status">{t('Gjenopprettingsadressen er lagret.')}</p>}</section>;
}
