'use client';
import {useEffect,useState,useRef} from 'react';
import {LanguagePicker,useLanguage} from '@/components/language';
export default function ResetPassword(){
 const initialized=useRef(false);
 const {t,language}=useLanguage();const [token,setToken]=useState(''),[ready,setReady]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[done,setDone]=useState(false);
 useEffect(()=>{if(initialized.current)return;initialized.current=true;setToken(window.location.hash.slice(1));window.history.replaceState(null,'',window.location.pathname);setReady(true)},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setMessage('');if(token&&password!==confirm){setError('De nye passordene er ikke like.');return}setBusy(true);try{const response=await fetch('/api/password-reset',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(token?{action:'reset',token,password}:{action:'request',email,language})});const data=await response.json() as {error?:string;message?:string};if(!response.ok)throw new Error(data.error);if(token){setDone(true);setToken('');setPassword('');setConfirm('')}else setMessage(data.message||'')}catch(e){setError(e instanceof Error?e.message:'Prøv igjen.')}finally{setBusy(false)}}
 return <><header><a className="brand" href="/">Steam</a><LanguagePicker/></header><main><section className="panel login"><h1>{t(done?'Passordet er endret':token?'Velg nytt passord':'Glemt passord?')}</h1>{done?<p role="status">{t('Logg inn med det nye passordet.')}</p>:<><p className="muted">{t(token?'Lenken kan bare brukes én gang.':'Oppgi e-postadressen som er lagret for gjenoppretting i admin.')}</p><form onSubmit={submit}>{token?<><label>{t('Nytt passord')}<input type="password" required minLength={8} maxLength={200} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>{t('Bekreft nytt passord')}<input type="password" required minLength={8} maxLength={200} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label></>:<label>{t('E-post')}<input type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>}<button className="primary" disabled={!ready||busy}>{t(busy?'Vennligst vent…':token?'Lagre nytt passord':'Send reset-lenke')}</button></form></>}{error&&<p className="error" role="alert">{t(error)}</p>}{message&&<p className="success" role="status">{t(message)}</p>}<p style={{marginTop:24}}><a href="/admin">{t('Tilbake til innlogging')}</a></p>{!!token&&<p><a href="/reset-password">{t('Be om en ny lenke')}</a></p>}</section></main></>;
}
